"""
Django settings for djangoproject project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
import json
from django.core.exceptions import ImproperlyConfigured
from celery.beat import crontab


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
with open(os.path.join(BASE_DIR, "secrets.json")) as f:
    secrets = json.load(f)
def get_secret(setting, secret=secrets):
    """Get secret setting or fail with ImproperlyConfigured"""
    try:
        return secret[setting]
    except KeyError:
        raise ImproperlyConfigured("Set the {} setting".format(setting))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = get_secret('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


ALLOWED_HOSTS = ["postgredjango.ew.r.appspot.com" ,
                 'localhost',
                 "127.0.0.1",
                 '192.168.0.65']



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django_extensions',
    'REST',
    'rest_framework',
    'rest_framework.authtoken',
    'django_filters',
    'website',    
    'corsheaders',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'mqtt_integration',
    'django_celery_beat',
    'celery',
    'django_celery_results',
    'AI',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sites.middleware.CurrentSiteMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'djangoproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR/'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                #'django.contrib.sites.context_processors.current_site',
            ],
        },
    },
]



WSGI_APPLICATION = 'djangoproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}
""" 
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'HOST': os.environ.get('DB_HOST', '127.0.0.1'),
        'NAME': 'database_di_prova',
        'USER': 'prova',
        'PASSWORD': 'ciao',
        'PORT': '5432',
    }
} """




# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/
STATIC_URL = 'static/'


# La cartella in cui sono raccolti i file statici durante la raccolta
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Le cartelle che contengono i file statici della tua applicazione
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'website/static'),
    # Altre cartelle, se presenti
]

# Default primary key field type


# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ALLOWED_ORIGINS = [
    "https://editor.swagger.io",
]


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
}

AUTH_USER_MODEL = 'REST.CustomUser'

AUTHENTICATION_BACKENDS = [
    'allauth.account.auth_backends.AuthenticationBackend',
]

ACCOUNT_EMAIL_VERIFICATION = 'optional'  # Può essere 'none', 'optional', 'mandatory'
ACCOUNT_UNIQUE_EMAIL = True

ACCOUNT_AUTHENTICATION_METHOD = 'username_email'
ACCOUNT_EMAIL_REQUIRED = True #Se l'utente è obbligato a fornire l'email quando si registra
ACCOUNT_USERNAME_REQUIRED = True #Se l'utente è obbligato a fornire l'username quando si registra
##Da tenere entrambe a True altrimenti non visualizzate nei form di signup e login


ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS = 1  # Giorni entro cui confermare l'email
ACCOUNT_EMAIL_SUBJECT_PREFIX = 'email di verifica'  # Personalizza il prefisso dell'oggetto dell'email
""" 
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id': 'il_tuo_client_id', #TODO: inserisci il tuo client id
            'secret': 'il_tuo_secret',
            'key': '',
        }
    },
    # Configura altri provider se necessario
}
 """
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False
EMAIL_HOST_USER = get_secret('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = get_secret('EMAIL_HOST_PASSWORD')


LOGIN_REDIRECT_URL = '/lista_master/'
ACCOUNT_LOGOUT_REDIRECT_URL = '/accounts/login/'

SITE_ID = 1  #TODO: Cambia a un ID di sito valido

    
#Per modificare i form di allauth volendo
ACCOUNT_FORMS = {
    'add_email': 'allauth.account.forms.AddEmailForm',
    'change_password': 'allauth.account.forms.ChangePasswordForm',
    'login': 'allauth.account.forms.LoginForm',
    'reset_password': 'allauth.account.forms.ResetPasswordForm',
    'reset_password_from_key': 'allauth.account.forms.ResetPasswordKeyForm',
    'set_password': 'allauth.account.forms.SetPasswordForm',
    'signup': 'allauth.account.forms.SignupForm',
    'user_token': 'allauth.account.forms.UserTokenForm',
}

#LOGIN_URL = '/accounts/login/'




#MQTT configuration
MQTT_BROKER_HOST = "localhost"
MQTT_BROKER_PORT = 1883  # Cambialo se necessario
MQTT_BROKER_KEEPALIVE = 60  # Cambialo se necessario
MQTT_QOS = 0
MQTT_USERNAME = '' #get_secret('MQTT_USERNAME')
MQTT_PASSWORD = '' #get_secret('MQTT_PASSWORD')
MQTT_CLIENT_ID = 'django_mqtt_client'
MQTT_TOPIC_IRRIGATORE = 'irrigatore/'


#CELERY configuration
#TODO per Filippo mettere indirizzo 127.0.0.1
WSL_IP_ADDR = get_secret('REDIS_SERVER_IP_ADDR')
CELERY_BROKER_URL = f'redis://{WSL_IP_ADDR}:6379/0'  # Sostituisci con la tua configurazione di Celery
CELERY_RESULT_BACKEND = CELERY_BROKER_URL
#CELERY_CACHE_BACKEND = 'django-cache'


CELERY_BEAT_SCHEDULE = {
    'refresh-misurazioni':{
        'task': 'REST.tasks.refresh_misurazioni',
        'schedule': crontab(minute=0, hour=0),  # Esegui ogni giorno a mezzanotte
    },
    'trigger-irrigatori': {
        'task': 'REST.tasks.trigger_irrigatori',
        'schedule': crontab('*/15'),  # Esegui ogni quarto dell'ora
    },
    # Aggiungi altri task periodici se necessario
}



#Irrigazione logic
UMIDITA_MINIMA_IRRIGAZIONE = 30  # Umidità minima per avviare l'irrigazione
THRESHOLD_IRRIGAZIONE = ...  # Sostituisci con il valore di soglia per l'irrigazione