# Generated by Django 4.2.7 on 2023-11-13 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REST', '0002_rename_idrometro_igrometro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='igrometro',
            name='data_creazione',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='masterigrometri',
            name='data_creazione',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
