# Generated by Django 4.2.7 on 2023-11-23 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('REST', '0006_customuser_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Irrigatore',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('latitudine', models.FloatField()),
                ('longitudine', models.FloatField()),
                ('data_creazione', models.DateTimeField(auto_now_add=True, null=True)),
                ('quota', models.FloatField()),
                ('attivo', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='irrigatori', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
