# Generated by Django 4.2.10 on 2024-02-11 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REST', '0009_irrigatore_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='irrigatore',
            name='durata_ultima_irrigazione',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='irrigatore',
            name='ultima_irrigazione',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
